version: "3.7"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=migration-user
      - POSTGRES_DB=migration-test
